apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service }}
  labels:
    app.kubernetes.io/name: {{ .Values.service }}
    app.kubernetes.io/part-of: {{ .Values.team }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.service }}
  ports:
    - { port: 80, targetPort: http, name: http }
