apiVersion: v1
kind: Service
metadata:
  name: cart
  labels:
    app.kubernetes.io/name: cart
    app.kubernetes.io/part-of: checkout
spec:
  selector:
    app.kubernetes.io/name: cart
  ports:
    - port: 80
      targetPort: http
      name: http
